export default [
		{
			ukr: "Я вже це бачив.",
			eng: "I have already seen it.",
			id : 1,
			type: 'present perfect',
		},
		{
			ukr: "Я саме зробив це.",
			eng: "I have just done it.",
			id : 2,
			type: 'present perfect',
		},
		{
			ukr: "Я саме поснідав.",
			eng: "I have just had breakfast.",
			id : 3,
			type: 'present perfect',
		},
		{
			ukr: "Я тільки що зателефонував їй.",
			eng: "I have just called her.",
			id : 4,
			type: 'present perfect',
		},
		{
			ukr: "Вона тільки що завершила.",
			eng: "She has just finished.",
			id : 5,
			type: 'present perfect',
		},
		{
			ukr: "Ви коли-небудь були там?",
			eng: "Have you ever been there?",
			id : 6,
			type: 'present perfect',
		},
		{
			ukr: "Я ніколи не був у Японії.",
			eng: "I have never been in Japan.",
			id : 7,
			type: 'present perfect',
		},
		{
			ukr: "Я знаю його 20 років.",
			eng: "I have known him for 20 years.",
			id : 8,
			type: 'present perfect',
		},
		{
			ukr: "Я знаю його з 1995.",
			eng: "I have known him since 1995.",
			id : 9,
			type: 'present perfect',
		},
		{
			ukr: "Він був там багато разів.",
			eng: "He has been there many times.",
			id : 10,
			type: 'present perfect',
		},
		{
			ukr: "Вони переїхали нещодавно.",
			eng: "They have moved recently.",
			id : 11,
			type: 'present perfect',
		},
		{
			ukr: "Я ще не був там.",
			eng: "I haven't been there yet.",
			id : 12,
			type: 'present perfect',
		},
		{
			ukr: "Вона ще не повернулася.",
			eng: "She hasn't come back yet.",
			id : 13,
			type: 'present perfect',
		},
		{
			ukr: "Ви коли-небудь відвідували це місце?",
			eng: "Have you ever visited this place?",
			id : 14,
			type: 'present perfect',
		},
		{
			ukr: "Ви вже пішли в тренажерний зал?",
			eng: "Have you already gone to the gym?",
			id : 15,
			type: 'present perfect',
		},
		{
			ukr: "Де ти був весь цей час?",
			eng: "Where have you been all this time?",
			id : 16,
			type: 'present perfect',
		},
		{
			ukr: "Я знаю Джима 10 років.",
			eng: "I have known Jim for 10 years.",
			id : 17,
			type: 'present perfect',
		},
		{
			ukr: "Ми володіємо цією машиною з 2012.",
			eng: "We have owned this car since 2012.",
			id : 18,
			type: 'present perfect',
		},
		{
			ukr: "Я вже випив 4 склянки вина.",
			eng: "I have already drunk 4 glasses of wine.",
			id : 19,
			type: 'present perfect',
		},
		{
			ukr: "Ми написали 2 сторінки есе досі.",
			eng: "We have written 2 pages of the essay so far.",
			id : 20,
			type: 'present perfect',
		},
		{
			ukr: "Сьюзен ще не обрала правильного місця для її відпустки.",
			eng: "Susan hasn't chosen the right place for her holidays yet.",
			id : 21,
			type: 'present perfect',
		},
		{
			ukr: "Його син спакував його чемодан?",
			eng: "Has his son packed his suitcase?",
			id : 22,
			type: 'present perfect',
		},
		{
			ukr: "Я завжди хотів поїхати до Бразилії.",
			eng: "I have always wanted to go to Brazil.",
			id : 23,
			type: 'present perfect',
		},
		{
			ukr: "Ви купили все що нам потрібно?",
			eng: "Have you bought everything we need?",
			id : 24,
			type: 'present perfect',
		},
		{
			ukr: "Я пробіг 21 кілометр до цього часу.",
			eng: "I have run 21 kilometers so far.",
			id : 25,
			type: 'present perfect',
		},
		{
			ukr: "Кейт відвідала всі основні міста у Єгипті.",
			eng: "Kate has visited all major cities in Egypt.",
			id : 26,
			type: 'present perfect',
		},
		{
			ukr: "Том намалював 3 чудові картини цього року.",
			eng: "Tom has painted 3 wonderful pictures this year.",
			id : 27,
			type: 'present perfect',
		},
		{
			ukr: "Ти вже зробив твою домашню роботу?",
			eng: "Have you done your homework yet?",
			id : 28,
			type: 'present perfect',
		},
		{
			ukr: "Ви прибирали вашу кімнату цього тижня?",
			eng: "Have you cleaned your room this week?",
			id : 29,
			type: 'present perfect',
		},
		{
			ukr: "Я ще не читав його останню книгу.",
			eng: "I haven't read his last book yet.",
			id : 30,
			type: 'present perfect',
		},
		// // //
		{
			ukr: "Якщо ви будете наполегливо навчатись, ви пройдете всі іспити.",
			eng: "If you study hard, you will pass all of the exams.",
			id : 31,
			type: 'first conditional',
		},
		{
			ukr: "Я допоможу вам полагодити машину, якщо ви не будете знати що робити.",
			eng: "I will help you to fix the car if you don't know what to do.",
			id : 32,
			type: 'first conditional',
		},
		{
			ukr: "Якщо ви не підете до лікаря, ви будете мати серйозні проблеми.",
			eng: "If you don't go to a doctor, you will have serious problems.",
			id : 33,
			type: 'first conditional',
		},
		{
			ukr: "Якщо вам потрібно зробити покупки, я допоможу вам носити сумки.",
			eng: "If you need to do the shopping, I will help you to carry the bags.",
			id : 34,
			type: 'first conditional',
		},
		{
			ukr: "Якщо ви не поспішите, ми пропустимо літак.",
			eng: "If you don't hurry, we will miss the plane.",
			id : 35,
			type: 'first conditional',
		},
		{
			ukr: "Ти допоможеш мені, якщо я не зрозумію завдання?",
			eng: "Will you help me if I don't understand the task?",
			id : 36,
			type: 'first conditional',
		},
		{
			ukr: "Ви витратите багато грошей, якщо ви зподорожуєте до Майорки у відпустку.",
			eng: "You will spend a lot of money if you travel to Majorca on holiday.",
			id : 37,
			type: 'first conditional',
		},
		{
			ukr: "Якщо ви не заощадите гроші, ви не підете у відпустку.",
			eng: "If you don't save money, you won't go on holiday.",
			id : 38,
			type: 'first conditional',
		},
		{
			ukr: "Ти зателефонуєш мені, якщо ти знайдеш ключі вдома?",
			eng: "Will you call me if you find the keys at home?",
			id : 39,
			type: 'first conditional',
		},
		{
			ukr: "Якщо погода буде приємна, ми підемо в плавання.",
			eng: "If the weather is nice, we will go sailing.",
			id : 40,
			type: 'first conditional',
		},
];
