export default [
		{
			ukr: "Вона написала статтю та бажає її опублікувати.",
			eng: "She has written an article and wants to publish it.",
			id : 1,
			type: 'perfect',
		},
		{
			ukr: "Джеймс вибрав машину та бажає її купити.",
			eng: "James has chosen a car and wants to buy it.",
			id : 2,
			type: 'perfect',
		},
		{
			ukr: "Ти приготував домашнє завдання на завтра? - Так, приготував.",
			eng: "Have you prepared your homework for tomorrow? - Yes, I have.",
			id : 3,
			type: 'perfect',
		},
		{
			ukr: "Ви прочитали цю книгу? - Ні, ми ні.",
			eng: "Have you read this book? - No, we haven't.",
			id : 4,
			type: 'perfect',
		},
		{
			ukr: "Вони вже вибрали машину? - Так, вони так",
			eng: "Have they already chosen a car? - Yes, they have.",
			id : 5,
			type: 'perfect',
		},
		{
			ukr: "Ви були в Англії?",
			eng: "Have you been in England?",
			id : 6,
			type: 'perfect',
		},
		{
			ukr: "Я загубив свої ключі і не можу їх знайти.",
			eng: "I have lost my keys and I can't find them.",
			id : 7,
			type: 'perfect',
		},
		{
			ukr: "Ти вже бачила моїх друзів? Вони з Португалії.",
			eng: "Have you seen my friends already? They are from Portugal.",
			id : 8,
			type: 'perfect',
		},
		{
			ukr: "Софія приготувала вечерю.",
			eng: "Sophie has cooked dinner.",
			id : 9,
			type: 'perfect',
		},
		{
			ukr: "Що ти купив? - Трохи молока та хліба.",
			eng: "What have you bought? - Some milk and bread.",
			id : 10,
			type: 'perfect',
		},
		{
			ukr: "Ти написав листа вже? - Так, написав.",
			eng: "Have you written a letter already? - Yes, I have.",
			id : 11,
			type: 'perfect',
		},
		{
			ukr: "Що вы купили? - Ми купили овощи та рыбу.",
			eng: "What have you bought? - We have bought vegetables and fish.",
			id : 12,
			type: 'perfect',
		},
		{
			ukr: "Вони вже поїли? - Ні ще.",
			eng: "Have they already eaten? - Not yet.",
			id : 13,
			type: 'perfect',
		},
		{
			ukr: "Джейн повернулася зі школи. Вона зараз вдома.",
			eng: "Jane has come back from school. She is at home now.",
			id : 14,
			type: 'perfect',
		},
		{
			ukr: "Холодно, вони закрили вікно.",
			eng: "It's cold, they have closed the window.",
			id : 15,
			type: 'perfect',
		},
		{
			ukr: "Він відкрив книгу на сторінці 18.",
			eng: "He has opened the book at page eighteen.",
			id : 16,
			type: 'perfect',
		},
		{
			ukr: "Сьогодні ми ходили в театр з нашими колегами.",
			eng: "Today we have gone to the theater with our colleagues.",
			id : 17,
			type: 'perfect',
		},
		{
			ukr: "Я хочу поговорити з тобою, ти закрив двері?",
			eng: "I want to talk to you, have you closed the door?",
			id : 18,
			type: 'perfect',
		},
		{
			ukr: "Моя мама дозволила мені піти на прогулянку.",
			eng: "My mother has allowed me to go for a walk.",
			id : 19,
			type: 'perfect',
		},
		{
			ukr: "Джеррі вже написав статтю, ми її скоро побачимо в газетах.",
			eng: "Jerry has already written his article, we'll see it soon in the newspapers.",
			id : 20,
			type: 'perfect',
		},
];
